server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./build/h2db/db/scheduler;
    username: scheduler
    password:
